# Powerlevel10k colors - Catppuccin Mocha
# Sourced by ktheme function after p10k loads

# Prompt character
POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=#89b4fa

# Directory
POWERLEVEL9K_DIR_FOREGROUND=#89b4fa
POWERLEVEL9K_DIR_BACKGROUND=#313244

# Git
POWERLEVEL9K_VCS_FOREGROUND=#cba6f7
POWERLEVEL9K_VCS_BACKGROUND=#313244
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=#a6e3a1
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=#f9e2af
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=#f38ba8

# Command execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=#f9e2af
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=#313244

# SSH
POWERLEVEL9K_SSH_FOREGROUND=#fab387
POWERLEVEL9K_SSH_BACKGROUND=#313244

# Virtual env
POWERLEVEL9K_VIRTUALENV_FOREGROUND=#94e2d5
POWERLEVEL9K_VIRTUALENV_BACKGROUND=#313244

# Status
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=#f38ba8
