# Powerlevel10k colors - Gruvbox Dark
# Sourced by ktheme function after p10k loads

# Prompt character
POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=#83a598

# Directory
POWERLEVEL9K_DIR_FOREGROUND=#83a598
POWERLEVEL9K_DIR_BACKGROUND=#3c3836

# Git
POWERLEVEL9K_VCS_FOREGROUND=#d3869b
POWERLEVEL9K_VCS_BACKGROUND=#3c3836
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=#b8bb26
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=#fabd2f
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=#fb4934

# Command execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=#fabd2f
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=#3c3836

# SSH
POWERLEVEL9K_SSH_FOREGROUND=#fe8019
POWERLEVEL9K_SSH_BACKGROUND=#3c3836

# Virtual env
POWERLEVEL9K_VIRTUALENV_FOREGROUND=#8ec07c
POWERLEVEL9K_VIRTUALENV_BACKGROUND=#3c3836

# Status
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=#fb4934
