# Powerlevel10k colors - Tokyo Night
# Sourced by ktheme function after p10k loads

# Prompt character
POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=#7aa2f7

# Directory
POWERLEVEL9K_DIR_FOREGROUND=#7aa2f7
POWERLEVEL9K_DIR_BACKGROUND=#1a1b26

# Git
POWERLEVEL9K_VCS_FOREGROUND=#bb9af7
POWERLEVEL9K_VCS_BACKGROUND=#1a1b26
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=#9ece6a
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=#e0af68
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=#f7768e

# Command execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=#e0af68
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=#1a1b26

# SSH
POWERLEVEL9K_SSH_FOREGROUND=#ff9e64
POWERLEVEL9K_SSH_BACKGROUND=#1a1b26

# Virtual env
POWERLEVEL9K_VIRTUALENV_FOREGROUND=#7dcfff
POWERLEVEL9K_VIRTUALENV_BACKGROUND=#1a1b26

# Status
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=#f7768e
