# Powerlevel10k colors - Current (dark blue-gray)
# Sourced by ktheme function after p10k loads

# Prompt character
POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=#56CCF2

# Directory
POWERLEVEL9K_DIR_FOREGROUND=#0077C8
POWERLEVEL9K_DIR_BACKGROUND=none

# Git
POWERLEVEL9K_VCS_FOREGROUND=#9B51E0
POWERLEVEL9K_VCS_BACKGROUND=none
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=#27AE60
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=#F2C94C
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=#EB5757

# Command execution time
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=#F2C94C

# SSH
POWERLEVEL9K_SSH_FOREGROUND=#F2994A

# Virtual env
POWERLEVEL9K_VIRTUALENV_FOREGROUND=#9B51E0

# Status
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=#EB5757

# Background colors for segments
POWERLEVEL9K_DIR_BACKGROUND=#1C232B
POWERLEVEL9K_VCS_BACKGROUND=#1C232B
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=#1C232B
POWERLEVEL9K_SSH_BACKGROUND=#1C232B
POWERLEVEL9K_VIRTUALENV_BACKGROUND=#1C232B
