# Current custom theme
background            #1C232B
foreground            #D0D0D0
cursor                #56CCF2
selection_background  #2D3748
selection_foreground  #FFFFFF

color0   #1C232B
color1   #EB5757
color2   #27AE60
color3   #F2C94C
color4   #2D9CDB
color5   #9B51E0
color6   #56CCF2
color7   #D0D0D0
color8   #606060
color9   #EB5757
color10  #27AE60
color11  #F2994A
color12  #56CCF2
color13  #BB6BD9
color14  #56CCF2
color15  #FFFFFF
